/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.strangegrotto.montu;

import com.strangegrotto.montu.parse.firstparse.MontuInstanceBuildingVisitor;
import org.commonmark.ext.task.list.items.TaskListItemsExtension;
import org.commonmark.node.Node;
import org.commonmark.parser.Parser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Set;


public class App {
    // TODO replace with parameterized file
    // private static String FILEPATH = "/Users/zerix/junk/test-checklist.md";
    private static String FILEPATH = "/Users/zerix/gdrive/checklists-and-templates/packing-lists/planning-travel.md";

    private static int SUCCESS_EXIT_CODE = 0;
    private static int FAILURE_EXIT_CODE = 1;

    private static final Logger log = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) throws IOException {
        var extensions = Set.of(TaskListItemsExtension.create());
        var markdownParser = Parser.builder()
                .extensions(extensions)
                .build();

        var fileReader = new BufferedReader(new FileReader(FILEPATH));
        Node parseResult;
        try {
            parseResult = markdownParser.parseReader(fileReader);
        } catch (IOException e) {
            log.error("An error occurred parsing the markdown file", e);
            System.exit(FAILURE_EXIT_CODE);
            return;
        }

        var instanceBuildingVisitor = new MontuInstanceBuildingVisitor();
        parseResult.accept(instanceBuildingVisitor);

        var instance = instanceBuildingVisitor.getMontuInstance();

        instance.run();
    }
}
